### ISSUE TITLE
sm2 crypt 加密超过 32 字节就无法解密

### ISSUE THREAD

**Issue by nighthk3** [oldprincess/gmlib#1]
` src/publickey/sm2/sm2_encrypt.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/publickey/sm2/sm2_encrypt.c b/src/publickey/sm2/sm2_encrypt.c
index 27f6f32..8896db1 100644
--- a/src/publickey/sm2/sm2_encrypt.c
+++ b/src/publickey/sm2/sm2_encrypt.c
@@ -66,7 +66,7 @@ int sm2_encrypt(uint8_t* out,
         sm2_kdf_next(key_stream, &kdf);
         memxor(out, key_stream, in, size);
         *outl += size, out += size;
-        inl -= size;
+        in += size, inl -= size;
     }
 
     return ERR_NOERROR;`

非常感谢这个项目，这里有一个小错，请您有空纠正一下。

**Comment by oldprincess** [comment]
非常感谢！您提到的问题我已修复。这确实是我编程时的疏忽，再加上GM SM2文档中的测试样例较短，导致我没发现这个错误。非常感谢您帮我发现这个错误！
